### ISSUE TITLE
redeclaring method issue

### ISSUE THREAD

**Issue by Porcupine96** [crystal-community/icr#57] opened 2017-08-29 20:36 UTC
Redefining method with the same name causes that all previous usages of that method are recalled again.

For example:

![duplicate method call](http://imgur.com/47i88mq.png)

Is that expected behaviour?

**Comment by greyblake** [comment] 2017-08-30 09:16
Hey, thanks for reporting.

It's not what we'd like to see, but it's totally expected behaviour if you take into consideration how ICR is implemented: https://github.com/crystal-community/icr#how-does-it-work
Keep in mind, that ICR is not a proper REPL, but rather a very hacky workaround for something REPL-like.

You may see unexpected behaviour working with network, file system, random numbers...
Since there is no way to fix it, I am gonna close the issue.

**Closed by greyblake** 2017-08-30 09:16 UTC
